### ISSUE TITLE
Open port 1900 for UDP so that UPNP discovery answers are accepted

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost/yunohost#97]
According to : 
http://www.upnp-hacks.org/upnp.html

After a discovery request is sent over the network with UDP on port 1900, the response of other machines on the nework is sent over the same port (1900). 
By default, the port 1900 is closed, whereas it should be opened. 
I have tested on my instance. If the port is not opened, UPNP won't be accessible, if the port is open, UPNP is activated.

**Comment by M5oul** [comment]
Done in https://dev.yunohost.org/issues/30.
